{% set version = "0.10.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-optmatch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/optmatch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/optmatch/optmatch_{{ version }}.tar.gz
  sha256: 5130abea0a162ab0e4045ea4bb2748b134f649829b634613007254e8e91d4991

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'  # [win]
    - '*/Rblas.dll'  # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-dplyr
    - r-rlemon
    - r-tibble
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr
    - r-rlemon
    - r-tibble
    - libopenblas

test:
  commands:
    - $R -e "library('optmatch')"           # [not win]
    - "\"%R%\" -e \"library('optmatch')\""  # [win]

about:
  home: http://optmat.ch, https://github.com/markmfredrickson/optmatch
  license: MIT
  summary: Distance based bipartite matching using minimum cost flow, oriented to matching of treatment and control groups in observational studies ('Hansen' and 'Klopfer' 2006 <doi:10.1198/106186006X137047>). Routines are provided to generate distances from generalised linear models (propensity score matching), formulas
    giving variables on which to limit matched distances, stratified or exact matching directives, or calipers, alone or in combination.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - lightning-auriga

# Package: optmatch
# Version: 0.10.6
# Title: Functions for Optimal Matching
# Description: Distance based bipartite matching using minimum cost flow, oriented to matching of treatment and control groups in observational studies ('Hansen' and 'Klopfer' 2006 <doi:10.1198/106186006X137047>). Routines are provided to generate distances from generalised linear models (propensity score matching), formulas giving variables on which to limit matched distances, stratified or exact matching directives, or calipers, alone or in combination.
# Authors@R: c(person("Ben", "Hansen", role = "aut", email = "ben.hansen@umich.edu"), person("Mark", "Fredrickson", role = "aut", email = "mark.m.fredrickson@gmail.com"), person("Josh", "Errickson", role = c("cre","aut"), email = "jerrick@umich.edu"), person("Josh", "Buckner", role = "aut"), person("Adam", "Rauh", role = "ctb"))
# LazyData: true
# Depends: R (>= 3.5.0)
# LinkingTo: Rcpp
# Imports: Rcpp, dplyr, stats, tibble, methods, graphics, rlemon
# Suggests: RItools, boot, biglm, survey, testthat (>= 0.11.0), roxygen2, brglm, arm, knitr, rmarkdown, markdown, pander, xtable, rrelaxiv, magrittr
# Enhances: CBPS, haven
# License: MIT + file LICENSE
# License_is_FOSS: yes
# License_restricts_use: no
# URL: http://optmat.ch, https://github.com/markmfredrickson/optmatch
# BugReports: https://github.com/markmfredrickson/optmatch/issues
# Additional_repositories: https://errickson.net/rrelaxiv
# Collate: 'DenseMatrix.R' 'InfinitySparseMatrix.R' 'MCFSolutions.R' 'Ops.optmatch.dlist.R' 'Optmatch-package.R' 'RcppExports.R' 'abs.optmatch.dlist.R' 'boxplotMethods.R' 'caliper.R' 'complementarySlackness.R' 'data.R' 'deprecated.R' 'distUnion.R' 'edgelist.R' 'exactMatch.R' 'feasible.R' 'fill.NAs.R' 'fmatch.R' 'fullmatch.R' 'makedist.R' 'match_on.R' 'matched.R' 'matched.distances.R' 'matchfailed.R' 'max.controls.cap.R' 'mdist.R' 'min.controls.cap.R' 'optmatchS3.R' 'pairmatch.R' 'print.optmatch.R' 'print.optmatch.dlist.R' 'scores.R' 'solve_reg_fm_prob.R' 'solver.R' 'strata.R' 'stratumStructure.R' 'summary.ism.R' 'summary.optmatch.R' 'utilities.R' 'zzz.R' 'zzzDistanceSpecification.R'
# VignetteBuilder: knitr
# RoxygenNote: 7.2.3
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2023-02-06 19:59:02 UTC; josh
# Author: Ben Hansen [aut], Mark Fredrickson [aut], Josh Errickson [cre, aut], Josh Buckner [aut], Adam Rauh [ctb]
# Maintainer: Josh Errickson <jerrick@umich.edu>
# Repository: CRAN
# Date/Publication: 2023-02-07 08:22:29 UTC
